#!/usr/bin/env bash
# Remove what a build reproduces, and nothing else.
#
# The working tree does not say which of its directories matter. `deploy/` and `server/dist`
# sit at the same level and read the same way; one is regenerated by a command, the other is
# a host profile that nothing can bring back. Three lists in this repository each answer a
# neighbouring question — `.gitignore` what is not source, `.dockerignore` what does not ship,
# `tools/pack.sh` what a deployment needs — and none of them answers "may I delete this".
#
# This does, by doing it. A boundary that can be run is a boundary that can be checked, which
# is worth more than the same boundary explained in prose and drifting.
#
# What it will not touch is the interesting half, and it is printed on every run:
#
#   deploy/                     host profiles. Not derived, out of git by design, and if it
#                               goes the deployment configuration goes with it.
#   server/var/blobs            the development blob store: real encrypted content at real
#   server/var/backups          addresses, and copies of it. These begin at first RUN, not at
#   server/var/restore.epoch    build, and no build brings them back.
#   node_modules/               derived, but restoring it is a network operation and must be
#                               done from the same side of the machine that runs the code
#                               (AGENTS.md). Deleting it is a decision, not a side effect.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$here"

removed=()
gone() { [ -e "$1" ] || return 0; rm -rf "$1"; removed+=("$1"); }

# Read from the manifest rather than listed here, so a new workspace cannot be forgotten.
for w in $(node -p "require('./package.json').workspaces.join(' ')"); do
  gone "$w/dist"
done

# `shared/` is the one workspace whose output is not called dist: it emits declarations into
# types/, which is generated from shared/src all the same and restored by a rebuild.
gone shared/types

# The root workspace is the solution, and `npm run pack` is what it builds.
gone dist

# Blob stores written by tests (server/test/support/store.ts). `db:reset` sweeps these too;
# both places is deliberate — this is the command reached for when the database is fine.
gone server/var/tmp

if [ ${#removed[@]} -eq 0 ]; then
  echo "nothing to remove"
else
  printf 'removed %s\n' "${removed[@]}"
fi

cat <<'EOF'

kept, because no build brings these back:
  deploy/                  host profiles
  server/var/blobs         the development blob store
  server/var/backups       its copies
  server/var/restore.epoch the counter that outlives the database
  node_modules/            derived, but reinstall from the side that runs the code
EOF
